<?php

namespace App\Filament\Resources\UserResource\Widgets;

use App\Models\Bill;
use App\Models\User;
use DB;
use Filament\Widgets\BarChartWidget;
use Illuminate\Database\Eloquent\Model;

class BillChart extends BarChartWidget
{
    protected static ?string $heading = 'Chart';

    public ?Model $record;

    public static function canView(): bool
    {
        return auth()->user()->hasRole('super_admin'); // TODO: Change the autogenerated stub
    }


    /**
     * @param Model|null $record
     */
    public function setRecord(?Model $record): void
    {
        $this->record = $record;
    }

    /**
     * @return string|null
     */
    public function getHeading(): ?string
    {
        return $this->record?->name;
    }

    protected function getData(): array
    {

        $bills = Bill::where('user_id', $this->record?->id)
            ->where('status', 'complete')
            ->whereBetween('created_at', [now()->subMonths(3)->startOfMonth(), now()])
            ->selectRaw('MONTHNAME(created_at) as month, SUM(price) as total_purchases')
            ->groupBy('month')
            ->orderBy(DB::raw('MONTH(created_at)'))
            ->pluck('total_purchases', 'month')
            ->toArray();

        $bills2 = Bill::where('user_id', $this->record?->id)
            ->where('status', 'complete')
            ->whereBetween('created_at', [now()->subMonths(3)->startOfMonth(), now()])
            ->selectRaw('MONTHNAME(created_at) as month, SUM(price)-SUM(cost)-SUM(ratio) as total_purchases')
            ->groupBy('month')
            ->orderBy(DB::raw('MONTH(created_at)'))
            ->pluck('total_purchases', 'month')
            ->toArray();

        return [
            'datasets' => [
                [
                    'label' => 'مشتريات',
                    'data' => array_values($bills),
                    'backgroundColor' => 'rgba(255,125,50,1)',
                ],
                [
                    'label' => 'الأرباح الصافية',
                    'data' => array_values($bills2),
                    'backgroundColor' => 'rgba(50,125,255,1)',
                ],
            ],

            'labels' => array_keys($bills),
        ];
    }

}
