<?php

namespace App\Filament\Resources\NewUserResource\Pages;

use App\Filament\Resources\NewUserResource;
use App\Models\User;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListNewUsers extends ListRecords
{
    protected static string $resource = NewUserResource::class;

    public function mount(): void
    {
        abort_if(!auth()->user()->hasRole('super_admin'),403);
        parent::mount(); // TODO: Change the autogenerated stub
    }

    protected function getActions(): array
    {
        return [
//            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return User::whereDoesntHave('balances')->latest(); // TODO: Change the autogenerated stub
    }
}
