<?php

namespace App\Filament\Resources\BillResource\Pages;

use App\Enums\OrderStatusEnum;
use App\Filament\Resources\BillResource;
use Closure;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListBills extends ListRecords
{
    protected static string $resource = BillResource::class;

    protected function getActions(): array
    {
        return [
//            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()->when(!auth()->user()->hasRole('super_admin'),fn($query)=>$query->whereHas('user',fn($query)=>$query->where('users.user_id', auth()->id()))); // TODO: Change the autogenerated stub
    }


}
