<?php

namespace App\Filament\Widgets;

use App\Enums\BillStatusEnum;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget;

class BillsChartOfDays extends ApexChartWidget
{
    /**
     * Chart Id
     *
     * @var string
     */
    protected static string $chartId = 'billsChartOfDays';
    protected int|string|array $columnSpan = [
        'md' => 2,
        'xl' => 1,
    ];
    /**
     * Widget Title
     *
     * @var string|null
     */
    protected static ?string $heading = 'المبيعات اليومية خلال الشهر الحالي';
    public static function canView(): bool
    {
        return auth()->user()->hasRole('super_admin'); // TODO: Change the autogenerated stub
    }
    /**
     * Chart options (series, labels, types, size, animations...)
     * https://apexcharts.com/docs/options
     *
     * @return array
     */
    protected function getOptions(): array
    {

        $bill=DB::table('bills')->where('status',BillStatusEnum::COMPLETE->value)->whereBetween('created_at',[now()->startOfMonth(),now()->endOfMonth()])
            ->selectRaw('(SUM(price) - SUM(cost) -SUM(ratio)) as total , Day(created_at) as day')->groupByRaw('Day(created_at)')->get();
        return [
            'chart' => [
                'type' => 'area',
                'height' => 300,
            ],
            'series' => [
                [
                    'name' => 'BasicBarChart',
                    'data' => $bill->pluck('total')->toArray(),
                ],
            ],
            'xaxis' => [
                'categories' => $bill->pluck('day')->toArray(),
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'yaxis' => [
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'colors' => [fake()->hexColor],
            'stroke' => [
                'curve' => 'smooth',
            ],
            'dataLabels' => [
                'enabled' => true,
            ],
        ];
    }
}
