<?php

namespace App\Filament\Widgets;

use App\Enums\BillStatusEnum;
use App\Enums\OrderStatusEnum;
use App\Models\Order;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Leandrocfe\FilamentApexCharts\Widgets\ApexChartWidget;

class OnlineOrders extends ApexChartWidget
{

    public static function canView(): bool
    {
        return auth()->user()->hasRole('super_admin'); // TODO: Change the autogenerated stub
    }
    protected int|string|array $columnSpan = [
        'md' => 2,
        'xl' => 1,
    ];
    /**
     * Chart Id
     *
     * @var string
     */
    protected static string $chartId = 'OnlineOrders';

    /**
     * Widget Title
     *
     * @var string|null
     */
    protected static ?string $heading = 'المبيعات الأرقام خلال السنة الحالية';

    /**
     * Chart options (series, labels, types, size, animations...)
     * https://apexcharts.com/docs/options
     *
     * @return array
     */
    protected function getOptions(): array
    {

        $bill=DB::table('orders')

            ->where('status',OrderStatusEnum::COMPLETE->value)
            ->whereBetween('created_at',[now()->startOfYear(),now()])
            ->selectRaw('SUM(price) - SUM(cost) - SUM(ratio) as total , Month(created_at) as month')->groupByRaw('Month(created_at)')->get();
        return [
            'chart' => [
                'type' => 'area',
                'height' => 300,
            ],
            'series' => [
                [
                    'name' => 'OnlineChart',
                    'data' => $bill->pluck('total')->toArray(),
                ],
            ],
            'xaxis' => [
                'categories' => $bill->pluck('month')->toArray(),
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'yaxis' => [
                'labels' => [
                    'style' => [
                        'colors' => '#9ca3af',
                        'fontWeight' => 600,
                    ],
                ],
            ],
            'colors' => [fake()->hexColor],
            'stroke' => [
                'curve' => 'smooth',
            ],
            'dataLabels' => [
                'enabled' => true,
            ],
        ];
    }
}
