<?php

namespace App\Filament\Resources;

use App\Filament\Resources\BalanceResource\Pages;
use App\Filament\Resources\BalanceResource\RelationManagers;
use App\Models\Balance;
use Filament\Forms;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class BalanceResource extends Resource
{
    protected static ?string $model = Balance::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';
    protected static ?string $label = 'الأرصدة';
    protected static ?string $navigationLabel = 'الأرصدة';
    protected static ?string $pluralLabel = 'الأرصدة';
    protected static ?string $navigationGroup = 'الإعدادات';
    protected static function shouldRegisterNavigation(): bool
    {
        return auth()->user()->hasRole('super_admin'); // TODO: Change the autogenerated stub
    }
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('credit')->label('شحن رصيد'),
                Tables\Columns\TextColumn::make('debit')->label('سحب رصيد'),
                Tables\Columns\TextColumn::make('info')->label('البيان')->searchable()->sortable(),
                Tables\Columns\TextColumn::make('user.username')->label('الزبون')->sortable(),
                Tables\Columns\TextColumn::make('user.email')->label('الزبون')->sortable(),
                Tables\Columns\TextColumn::make('bill.uuid')->label('رقم الطلب'),
                Tables\Columns\TextColumn::make('created_at')->since()->label('منذ')->sortable(),
            ])->defaultSort('created_at','desc')
            ->filters([
                //
            ])
            ->actions([
//                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
//                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListBalances::route('/'),
//            'create' => Pages\CreateBalance::route('/create'),
//            'edit' => Pages\EditBalance::route('/{record}/edit'),
        ];
    }
}
