<?php

namespace App\Filament\Resources\ProductUserResource\Pages;

use App\Filament\Resources\ProductUserResource;
use App\Models\ProductUser;
use Filament\Notifications\Notification;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Database\Eloquent\Model;

class EditProductUser extends EditRecord
{
    protected static string $resource = ProductUserResource::class;

    protected function getActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        $prduct= ProductUser::updateOrCreate([
            'product_id'=>$data['product_id'],
            'user_id'=>$data['user_id'],
        ],[
            'price'=>$data['price']
        ]);
        Notification::make('success')->title('تمت العملية بنجاح')->success()->send();
        return $prduct;
//        return parent::handleRecordUpdate($record, $data); // TODO: Change the autogenerated stub
    }
}
