<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        if(!isset($data['group_id'])){
            $data['group_id']=auth()->user()->group_id;
        }
        if(!isset($data['user_id']) && !auth()->user()->hasRole('super_admin')){
            $data['user_id']=auth()->id();
        }
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
