<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use App\Models\User;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;

class EditUser extends EditRecord
{
    protected static string $resource = UserResource::class;

   public function mount($record): void
   {
      $user=User::findOr($record);
       abort_if(($user->user_id!=auth()->id() || (in_array($user->user_id,$user->users->pluck('user_id')->toArray())))&& !auth()->user()->hasRole('super_admin'),404);
       parent::mount($record); // TODO: Change the autogenerated stub
   }

   protected function getHeaderWidgets(): array
   {
       return array_merge(parent::getHeaderWidgets(),[UserResource\Widgets\BillChart::class]); // TODO: Change the autogenerated stub
   }

    protected function getActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
        if($this->record->is_fixed_group && !auth()->user()->hasRole('super_admin')){
            $data['group_id']=$this->record->group_id;
        }
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
