<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;
use Illuminate\Database\Eloquent\Builder;

class ListUsers extends ListRecords
{
    protected static string $resource = UserResource::class;

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    protected function getTableQuery(): Builder
    {
        return parent::getTableQuery()
            ->when(!auth()->user()->hasRole('super_admin') && auth()->user()->is_branch==false,
                fn($q)=>$q->where(['user_id'=>auth()->id()])
            ) // TODO: Change the autogenerated stub
            ->when(!auth()->user()->hasRole('super_admin') && auth()->user()->is_branch==true,
                fn($q)=>$q->where(['user_id'=>auth()->id()])->orWhereHas('user',fn($query)=>$query->where('user_id',auth()->id()))
            ); // TODO: Change the autogenerated stub
    }
}
